### ISSUE TITLE
Testing Deployment using a Staging Site: Relative path symlink causing nginx troubles 

### ISSUE THREAD

**Issue by KamilMalek** [hjwp/Book-TDD-Web-Dev-Python#79]
In the deployment guide after the nginx installation we perform steps to remove the default symlink and set up a proxy pass to django app on port 8000 using a command: 
``elspeth@server:$ sudo ln -s ../sites-available/$SITENAME /etc/nginx/sites-enabled/$SITENAME`` 

However nginx did not render the relative symlink. My suggestion would be to replace it with: 
``elspeth@server:$ sudo ln -s etc/nginx/sites-available/$SITENAME /etc/nginx/sites-enabled/$SITENAME``

And remove the relative paths in commands in general or add a ``pwd`` before them as it can take to reproduce the desired effect otherwise.

**Comment by hjwp** [comment]
this is strange.  A lot of people seem to have trouble with this symlink.  But symlinks with relative targets are evaluated relative to their own position in the filesystem, not to the place you were at the time you created them, so a `pwd` is irrelevant:

    cd ~  # cd into /home/username
    ln -s .. /tmp/symlinkey  # symlink target = ..
    ls /tmp/symlinkey/etc  # show /etc, not /home/etc



still, *something* must be going wrong because you aren't the only person to mention this.  I wonder what.

**Comment by hjwp** [comment]
fixed!  no more relative paths...
